### ISSUE TITLE
[Style] Automatic code formatting

### ISSUE THREAD

**Issue by sewera** [pocketbase/js-sdk#103]
When working on the project, I found myself doing
a bit of manual work with code formatting.

I think the best would be setting up [Prettier](https://prettier.io/),
as it's supported in most code editors,
including VSCode, which is used widely for JS/TS development.

Thus, I propose to add a `prettier.config.js`,
or better yet a `.prettierrc.json` file.

To match the current style as closely as possible,
I will suggest a Prettier config at a later time.

Let me know if you like this idea. Or, you can share an existing
formatter config if there is one.

**Comment by ganigeorgiev** [comment]
Let's not add this for now. I'm planning a refactoring in the near future to replace the `EventSource` dependency and I may consider adding a formatter but for TS projects most of the times this shouldn't be necessary since the LSP-TypeScript comes with code formatter that by default should be triggered after save (at least that's the case with the LSP plugin for Sublime - https://github.com/sublimelsp/LSP-typescript/issues/118).

**Comment by sewera** [comment]
Alright, I'll have to look into your formatter because it doesn't get triggered in VSCode by default, I think.

If you need any help with adding some formatter config, you can ping me here :)
