### ISSUE TITLE
Nuxt 3 example not working

### ISSUE THREAD

**Issue by HipyCas** [pocketbase/js-sdk#124]
When setting up Pocketbase with Nuxt 3 following the example in the README.md (using the plugin), the authstore is cleared every time I reload the page and I get this error constantly:

```
[nitro] [dev] [unhandledRejection] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client                                                                               02:23:02
    at new NodeError (node:internal/errors:388:5)
    at ServerResponse.setHeader (node:_http_outgoing:603:11)
    at setResponseHeader (file:///home/hipy/dev/mini-projs/openforms-nuxt3/node_modules/h3/dist/index.mjs:277:18)
    at Object.errorhandler [as onError] (file:///home/hipy/dev/mini-projs/openforms-nuxt3/.nuxt/dev/index.mjs:446:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server.toNodeHandle (file:///home/hipy/dev/mini-projs/openforms-nuxt3/node_modules/h3/dist/index.mjs:752:9) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce the issue when using only nuxt in a SSR context as it is in readme example.

If you are not able to make it work, you can try instead of manually setting response cookie header, to use the nuxt [`useCookie` helper](https://nuxt.com/docs/examples/composables/use-cookie#usecookie) since it will work in both browser and server (_note that if you want to use the cookie client-side you'll have to export it with `httpOnly: false`_).

_All SSR examples will be updated after the upcoming PocketBase v0.11.0 release._

**Comment by HipyCas** [comment]
> If you are not able to make it work, you can try instead of manually setting response cookie header, to use the nuxt [`useCookie` helper](https://nuxt.com/docs/api/composables/use-cookie) since it will work in both browser and server (_note that if you want to use the cookie client-side you'll have to export it with `httpOnly: false`_).

As far as I can read, `useCookie` only work for reading the cookie, where here the problems looks like it comes from setting the cookie. Am I getting something wrong? How would I use `useCookie` in the sending part?

Also, what version of Nuxt are you using to reproduce this?

**Comment by ganigeorgiev** [comment]
I've tested it only with the minimal template `npx nuxi init ...` (nuxt 3.0). I'm not very familiar with nuxt, but from the documentation of `useCookie`:

> Within your pages, components and plugins you can use useCookie, an SSR-friendly composable to read and **write cookies**.

The example in https://nuxt.com/docs/api/composables/use-cookie#example illustrates that modifying the returned object props will "update" the cookie value accordingly. Additionally at the bottom of the same page there is another alternative for setting cookies in an API route.

But this is just an abstraction to work with the browser/client-side and node/server-side cookie interfaces in an unified manner. The problem could be somewhere else (eg. unawaited promise that sets the cookie after the response has already been sent).

From a brief look at your code it seems that you are using a "mixed" approach, aka. both client-side and server-side access, **but the examples in the readme works within a server-side only context** (notice that we are calling the plugin in a `useAsyncData` hook).

I'll try to experiment a little more with nuxt and the other frontend frameworks and will update the examples in the near future (most likely next week), but currently the upcoming v0.11.0 release and the filter enhancements are with higher priority.

But in general, you don't have to follow the example directly since there is more than 1 way to handle this. The flow usually should be:

1. Create a new PocketBase instance for each server-side request
2. "Load/Feed" your `pb.authStore` with data from the request cookie
3. Perform your application server-side actions
4. **Before returning the response to the client**, update the cookie with the latest `pb.authStore` state
