### ISSUE TITLE
error during record creation in next.js

### ISSUE THREAD

**Issue by AbdulRehmanConqueror** [pocketbase/js-sdk#140]
when I try to insert a list of records, the data gets inserted successfully into a collection named "artists" but the below error occurs

Unhandled Runtime Error
ClientResponseError 0: The request was autocancelled. More info you can find at https://github.com/pocketbase/js-sdk#auto-cancellation.

Source
src\lib\seedData.ts (9:11) @ async eval
```

   7 | return artistsData.map(async (artist) => {
   8 |   console.log(artist);
>  9 |   return await pb.collection("artists").create({
     |         ^
  10 |     name: artist.name,
  11 |     songs: artist. songs.map((song) => {
  12 |       return {

```

And in the devtool console, the following errors occur

pocketbase.es.mjs?43fe:1 Uncaught (in promise) ClientResponseError 0: The request was autocancelled. More info you can find at https://github.com/pocketbase/js-sdk#auto-cancellation.
    at new ClientResponseError (pocketbase.es.mjs?43fe:1:2274)
    at eval (pocketbase.es.mjs?43fe:1:40238)
    at async eval (seedData.ts?bf43:9:12)

Failed to load resource: the server responded with a status of 400 (Bad Request)

Uncaught (in promise) ClientResponseError 400: Failed to create a record.
    at new ClientResponseError (pocketbase.es.mjs?43fe:1:2274)
    at eval (pocketbase.es.mjs?43fe:1:40238)
    at async eval (seedData.ts?bf43:9:12)

**Comment by ganigeorgiev** [comment]
The error message suggest that the request was auto cancelled.

You can read more about autocancellation in https://github.com/pocketbase/js-sdk#auto-cancellation.

You can disable completely the autocancellation behavior by defining `pb.autoCancellation(false)`.

But I don't recommend this because autocancellation helps identifying userland async bugs (eg. sending requests on button click without awaiting the previous ones to complete). The recommended way to handle autocancellation error is to `try/catch` them and ignore them if `err.isAbort` is `true`:

```js
try {
    await pb.collection("example").create({ ... });
} catch (err) {
    if (!err.isAbort) {
        console.log("Actual error...");
    }
}
```

**Comment by AbdulRehmanConqueror** [comment]
the main issue is that the records get created in pocketbase collection and I'm still getting the below error

Uncaught (in promise) ClientResponseError 400: Failed to create a record.
    at new ClientResponseError (pocketbase.es.mjs?43fe:1:2274)
    at eval (pocketbase.es.mjs?43fe:1:40238)
    at async eval (seedData.ts?bf43:11:14)
