### ISSUE TITLE
Easier way of switching storage API

### ISSUE THREAD

**Issue by lucaslevin** [pocketbase/js-sdk#142]
Really digging the library, but I am having a hard time dealing with the AuthStore on React Native. I know it is possible to implement own logic, but I feel like it would be a lot nicer if you could switch out localStorage out for something else much quicker. Could be AsyncStorage, or perhaps sessionStorage. I think it would benefit having it like this so people wouldn't have to rewrite logic just to save auth somewhere else than localStorage.

**Example (similar to Supabase, Zustand etc.)**
`const pb = new PocketBase('http://127.0.0.1:8090', { storage: () => AsyncStorage/sessionStorage);`

Hope it is something that is possible in the future as Pocketbase is truly something else. Loving the work being put into the project.

**Comment by ganigeorgiev** [comment]
We can provide a configuration option to the default `LocalAuthStore` to replace `localStorage` with any other api that supports the [`Storage` interface](https://developer.mozilla.org/en-US/docs/Web/API/Storage) but I don't think it will be very useful in general because technically you'll be able to replace it out of the box only with the native `sessionStorage`.
For example `AsyncStorage/sessionStorage`, while having the same method names as the `Storage` interface, it is not compatible with it because the api is async.

Additionally, I think most users will find it confusing to have an abstraction inside another abstraction. The better approach probably would be to implement individual `AuthStore`s inside the package so that users can "switch" by just replacing the instance during initialization:

```js
import PocketBase, { SomeCustomAuthStore } from 'pocketbase';

const pb = new PocketBase(url, new SomeCustomAuthStore())
```

But currently far more critical/blocker issues are in the [roadmap](https://github.com/orgs/pocketbase/projects/2) (_and I'm already behind the initial planned schedule for my other open source project [Presentator #183](https://github.com/presentator/presentator/issues/183)_) and at least for the near future I'm not planning to work on this.

Community provided stores are welcomed (the custom stores can even reside in their own repo using the SDK only as a peer-dependency).
