### ISSUE TITLE
How to properly subscribe to collection when using react

### ISSUE THREAD

**Issue by btalanski** [pocketbase/js-sdk#144]
I'm looking for some help implementing a subscription to a collection when using React and functional components.

I can't seem to find a good example online so I decided to ask here.

I understand the best place to subscribe would be using a `useEffect` hook but I tried and it won't work properly. This is an example of what I did:

```
  useEffect(() => {
    (async () => {
      await pb.collection('shopping_list').subscribe('*', (event) => { 
        console.log('shopping_list refreshing...');
        // Handle state updates when collection is updated
      });
    })();
    return () => {
      console.log('unsubscribe');
      pb.collection('shopping_list').unsubscribe();
    }
  },[]);
```

Subscription works alright but when time comes to unsubscribe the clean up function in use effect always throws an error.

**Comment by ganigeorgiev** [comment]
_Similar question was asked recently in https://github.com/pocketbase/pocketbase/discussions/1720._

I don't think this is related only to the SDK since you'll stumble on the same issue with any other library that deals with async calls.

One way to simplify the above would be to remove the `async/await` wrapping since it doesn't really do much in the above sample:

```js
useEffect(() => {
  pb.collection('shopping_list').subscribe('*', (event) => { 
    console.log('shopping_list refreshing...');
    // Handle state updates when collection is updated
  });

  return () => {
    console.log('unsubscribe');
    pb.collection('shopping_list').unsubscribe();
  }
}, []);
```
