### ISSUE TITLE
Optional authorization store per browser tab/window

### ISSUE THREAD

**Issue by auroraanna** [pocketbase/js-sdk#145]
In [kaufkauflist](https://codeberg.org/annaaurora/kaufkauflist), a web app I've been developing with this SDK, I had the problem that if I had one authorized browser tab open and then opened another which the second browser tab would overwrite the authorization store the first one was using when it authorized. I guess this is because those tabs were both on the same domain.

Is there a solution to this other than each tab authorizing if the authorization store changed before making a request to pocketbase? That's what kaufkauflist is doing currently. Could you, e.g. having an authorization store for each of those tabs? I didn't find anything like that in the documentation or SDK functions.

**Comment by ganigeorgiev** [comment]
In my opinion this should be the expected behavior by the consumers of your app.

What should be the auth state if the user reopen the browser - relogin again?
Should the previous auth state be preserved or the auth state should be valid only until they leave the page(aka. closing the tab/window)?

If you want a temporary/individual auth session per tab, then you can either define a new AuthStore or provide a different localStorage key for each tab:

```js
// define individual localStorage key some randome
// ---
import PocketBase, { LocalAuthStore } from "pocketbase";

const pb = new PocketBase('http://127.0.0.1:8090', new LocalAuthStore("some_random_key"));


// OR create a custom store that will keep the token only while the tab is open
// ---
import PocketBase, { BaseAuthStore } from 'pocketbase';

class TempAuthStore extends BaseAuthStore {
    save(token, model) {
        super.save(token, model);
    }

    clear() {
        super.clear();
    }
}

const pb = new PocketBase('http://127.0.0.1:8090', new TempAuthStore());
```

You can read more about the AuthStore in https://github.com/pocketbase/js-sdk#authstore
