### ISSUE TITLE
No issue, more a question: Best practice for handeling SSR and Client side OAuth 2 authentication 

### ISSUE THREAD

**Issue by PaulDotterer** [pocketbase/js-sdk#156]
Hello all,
im really loving this project and im currently building an application with it an SvelteKit.

I implemented all auth logic server side with the provides `hooks.server.js` example and it works perfectly fine.

I now want to add realtime subscriptions to my app. SvelteKit currently has no option to "proxy" SSE from backend to frontend, so i have to login the user from their browser.

My question is, how would i handle that type of flow?
Does the User will have to login 2 times, or am i missing something.

I have also tried logging in the user client side with the original generated access token, but that does not seem to work as expected.

Again, im sorry if i miss something or try to shoehorn logic in that is not appropriate.

I suppose the best option would be to just wait until SvelteKit implements SSE themselves.

**Comment by ganigeorgiev** [comment]
I'm little confused from the title and I'm not sure that I understand what the OAuth2 authentication has to do with the realtime subscriptions.

> Does the User will have to login 2 times, or am i missing something.

It depends. You can share the auth cookie with the client if you export with `{httpOnly: false}` (_note that any loaded js will have access to it and it is recommend to have a [CSP policy](https://github.com/pocketbase/js-sdk#security) configured_). Then on the client-side you can initialize a browser SDK instance, something like (_I haven't tested it_):

```js
import PocketBase from 'pocketbase';

const client = new PocketBase("http://127.0.0.1:8090");

client.authStore.loadFromCookie(document.cookie);

// in case of a client-side store change update the cookie string
client.authStore.onChange(() => {
    document.cookie = client.authStore.exportToCookie({ httpOnly: false });
})

export default client;
```

> I have also tried logging in the user client side with the original generated access token, but that does not seem to work as expected.

It should work just fine. Was there any error othen than 401/403? You can start PocketBase with `--debug` flag for more detailed messages or check the logs in the "Admin UI > Logs".

Also keep in mind that on success OAuth2 (or regular authentication), the PocketBase auth token is returned as `token` key.
You can't authenticate in PocketBase with the OAuth2 provider tokens returned in `meta.accessToken` or `meta.refreshToken`, if that is what you mean by "generated access token". The returned token(s) in the `meta` object works only within the provider apis.

---

> I suppose the best option would be to just wait until SvelteKit implements SSE themselves.

If you want to proxy the SSE events (_aka. as in client<--SSE--node<--SSE--PocketBase_), then I think this is already supported in SvelteKit using `ReadableStream` but I haven't tested it. From the [official docs](https://kit.svelte.dev/docs/routing#server):
> The first argument to Response can be a [ReadableStream](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream), making it possible to stream large amounts of data or create server-sent events (unless deploying to platforms that buffer responses, like AWS Lambda).

I'll close the issue because I'm not sure what else to recommend, but If you need further help, feel free to leave a comment.

**Comment by ganigeorgiev** [comment]
One side-note, if you decide to use the realtime services in node, you'll have to load an `EventSource` polyfill, because it is not natively supported:

```js
// npm install eventsource --save
import eventsource from 'eventsource';

global.EventSource = eventsource;

...
```

**Comment by PaulDotterer** [comment]
Thank you Gani for the detailed reply and the recommendations!
Im sorry for the confusing title, it does not have anything todo with realtime. Realtime was just the arising issue where i came across this question.

The generated access token was just the token returned by `authStore.exportToCookie()` function. I will check with more detailed logs. I just got a 401 error.

I will need to read up more on Readable streams, but it looks like what im missing.

Nevertheless, thank you for the recommendations and quick response!
