### ISSUE TITLE
Improve JS SDK values to maintain JS types

### ISSUE THREAD

**Issue by terehov** [pocketbase/js-sdk#157]
We're really enjoying working with Pocketbase as it's the perfect tool for our use case. However, as we're working in a JavaScript/TypeScript context, it would be great if the JS SDK values were maintained as JS types.

Currently, we are helping ourselves with two helpers functions for `null` values and date fields. It would be beneficial if a SQLite `null` value was also represented as a `null` value in JavaScript, instead of an empty string. Additionally, it would be helpful if a date field was returned as a date object or at least an ISO string.

To work around these issues, we're currently using the following helper functions:

```typescript
// Workaround for pocketbase having empty strings as a null value
export function isPocketbaseNull(value: any): boolean {
  return value == null || value?.toString() === "";
}

// Workaround for pocketbase not returning ISO date string
export function pocketbaseDatetimeToISO(dateTimeStr: string): string {
  return dateTimeStr.replace(" ", "T");
}
```

**Comment by ganigeorgiev** [comment]
PocketBase doesn't support `null` as field values (with exception of the `json` type field), meaning that even if you submit a `null` as value for a `text` field it will be stored and returned as empty string. For a list with the supported field values you can check https://pocketbase.io/docs/collections/#overview.

The datetime string is actually compatible with ISO8601 and it is just an alternative format (aka. you should be able to use `new Date("2022-02-27 10:00:20.123Z")`). We use space as delimiter to preserve the backward compatibility (you can read more in https://github.com/pocketbase/pocketbase/issues/472#issuecomment-1255056640).

**Comment by terehov** [comment]
I see. Thank you for the clarification. Feels a bit odd to get an empty string for a date field though. 

In terms of ISO8601: It works most of the use cases, but not on Safari (15.6.1 (17613.3.9.1.16))

**Comment by ganigeorgiev** [comment]
> In terms of ISO8601: It works most of the use cases, but not on Safari (15.6.1 (17613.3.9.1.16))

Hm, I don't have Safari to test it, but it seems that per the [ECMASCript spec](https://262.ecma-international.org/6.0/#sec-date-time-string-format) doesn't fully implement the iso8601 format and indeed it is possible that the datetime string without `T` as separator may not be considered valid by all browsers.

At least for now, we can't replace the space separator since it will be a major breaking change. Eventually in the future we may add support for normalizations for the filter arguments (eg. https://github.com/pocketbase/pocketbase/issues/602#issuecomment-1259882406) and may apply the change in backward compatible manner, but for now remains out of the scope of v1.
