### ISSUE TITLE
Should Storage fallback be static?

### ISSUE THREAD

**Issue by MHDante** [pocketbase/js-sdk#163]
Reading through the implementation, there seems to be a difference in semantics between browser and node usage. 

In browser, multiple instances of LocalAuthStore will have the same information, while in Node, they will contain different info.

This can be addressed by storing the storage fallback as a static object (although this may introduce multi-threading concerns)

https://github.com/pocketbase/js-sdk/blob/fc94f2354350465246f32653e0374ecfa878538a/src/stores/LocalAuthStore.ts#L10

**Comment by ganigeorgiev** [comment]
I'm not planning changing the current AuthStore implementation. If you need custom store, you can implement it on your own and provide it as a constructor argument during initialization:

```js
const pb = new PocketBase('http://127.0.0.1:8090', new CustomAuthStore());
```

---

For browser - if you want to have different AuthStore instances, you can explicitly set a localStorage key. But most of the time you want to share the same auth state.

For node - you usually would want the opposite - separate SDK instances each with their own store because otherwise requests from different users will overwrite/conflict on the same `pb.authStore` state. This is also why in the [SSR example](https://github.com/pocketbase/js-sdk#ssr-integration) it is mentioned that you need to provide a new PocketBase SDK instance for each server-side request (eg. usually stored like local/context prop as part of the request object).
