### ISSUE TITLE
client.Records.getList with date filter

### ISSUE THREAD

**Issue by mbecker** [pocketbase/js-sdk#17]
Hi,

I have a collection `activities` with a field / column `start_date` which is defined as a `Date`. I want to request only records later than a specific date.

The code is as follows:
```javascript
const result = await client.Records.getList(
          "activities",
          1,
          20,
          {
            sort: "-start_date",
            filter: `start_date > ${new Date('2022-07-23 16:08:05')}`
          },
        );
```

Any format of the `new Date('xxx')` like `toISOString()` or `toUTCString()` results in the same errors (different query param for the date, of course). The filter does work for formats like `start_data > 2022`.

This results in the following url and error
```sh
pocketbase.es.mjs?ab5d:1          GET http://localhost:8090/api/collections/activities/records?page=1&perPage=20&filter=start_date%20%3E%202022-07-23%2016%3A08%3A05 400 (Bad Req

# Detailed error message
ClientResponseError 400: Invalid filter parameters.
    at new i (pocketbase.es.mjs?ab5d:1:2067)
    at eval (pocketbase.es.mjs?ab5d:1:23321)
```

Does it work to filter records by a `Date`? Thanks for any help!

**Comment by ganigeorgiev** [comment]
You cannot pass directly a JS object to the filter.

In your example it fails with _"Invalid filter params"_ error because the date must be set as string, aka. wrapped with single or double quotes (otherwise the filter will try to look for a field name matching the identifier and because it doesn't exist it throws an error).

This is not documented, but the dates are expected to be in the format `"Y-m-d H:i:s.u"` (or any part of it, eg. `"Y-m-d"`). `toISOString()` and `toUTCString()` returns a different format so you'll have to construct it manually or use a date library that supports specifying the output format.

**Comment by mbecker** [comment]
Great! Does work! 

The following should do the trick:
```javscript
let dt = new Date('2022-07-23 16:08:05');
const result = await client.Records.getList(
  "activities",
  1,
  20,
  {
    sort: "-start_date",
    filter: `start_date > "${dt.toISOString().replace("T", " ").replace("Z", "")}"`
  },
);
```
