### ISSUE TITLE
Query about 'pocketbase_auth' local storage on redirect/state change

### ISSUE THREAD

**Issue by Elliott-Green** [pocketbase/js-sdk#173]
Hey.

I have a SK page which directs to a Stripe checkout page when a user is logged in. On Stripe success/error, it'll respond with a redirect to the browser to go to a defined success/error page. 

Prior to directing to Stripe, I have a 'pocketbase_auth' local storage set with a token and model. 
After Stripe, I am redirected back to my SK app, the  'pocketbase_auth' local storage is now unset, prompting the user to log back in. 

I am updating the logged in user row as part of that Stripe success process. But as a test, I manually changed the data and it doesn't cause a logout. Wondering if this has anything to do with the redirect? Everything seems to be 200 with no errors/restarts. 

Any ideas what I can investigate next?

**Comment by ganigeorgiev** [comment]
Are you using cookies? Could you provide a code sample how you initialize the SDK?

In general if you are not loading manually a cookie, the client-side SDK's AuthStore shouldn't be affected by the redirect unless there is something that manually calls `pb.authStore.clear()`.

**Comment by Elliott-Green** [comment]
Yeah, I'm using cookies - seems like on the redirect, it doesn't have it available as I get the negative log line.

```bash
...
✅ STRIPE - checkout.session.completed ✅
in server hooks after
in server hooks before
Couldn't load auth cookie
...
```

hooks.server.ts
```ts
import { pb } from '$lib/pocketbase/pocketbase';
import type { Handle } from '@sveltejs/kit';

export const handle: Handle = async ({ event, resolve }) => {
	// before
	console.log(`in server hooks before`);
	pb.authStore.loadFromCookie(event.request.headers.get('cookie') || '');
	if (pb.authStore.isValid) {
		console.log(`loaded auth cookie!`);
		try {
			await pb.collection('users').authRefresh();
		} catch (_) {
			pb.authStore.clear();
		}
	} else {
		console.log(`Couldn't load auth cookie`);
	}

	event.locals.pb = pb;
	event.locals.user = structuredClone(pb.authStore.model);

	const response = await resolve(event);
	console.log(`in server hooks after`);
	// after
	response.headers.set('set-cookie', pb.authStore.exportToCookie({ httpOnly: false }));

	return response;
};
```

pocketbase/pocketbase.ts
```ts
import PocketBase from 'pocketbase'
import { localStorageStore } from '@skeletonlabs/skeleton';
import { writable, type Writable } from 'svelte/store';

export const pb = new PocketBase(import.meta.env.VITE_POCKETBASE_URL)

export const currentUser = writable(pb.authStore.model)
//export const currentUser: Writable<any> = localStorageStore('session', pb.authStore.model);
```

**Comment by ganigeorgiev** [comment]
Hm, there are several possible issues here.

1. Is the `pocketbase.ts` in browser, node or both?
   If the SDK is initialized in a node env, you need to create a new SDK instance on every request, otherwise requests from different users will write over the same `pb.authStore`.

2. By default the cookie is exported with `SameSite=Strict`, so that when the user send request to stripe it will not send the pb cookie with it, meaning that after the stripe->node redirect you'll not have an auth cookie and will write an empty cookie to the response (at least that is what I guess is happening). One workaround could be to export the cookie with `sameSite: Lax` but make sure to check [SameSite cookies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite) and [SameSite cookies explained](https://web.dev/samesite-cookies-explained/).

btw. If you don't use the SDK instance in a client-side/browser env, you can also skip the `httpOnly: false`. This flag is needed only if you want to access the cookie with JS in the browser.
