### ISSUE TITLE
Auth with Microsoft is not working

### ISSUE THREAD

**Issue by Artur-Galstyan** [pocketbase/js-sdk#176]
To recreate:

1. Create a Microsoft Project
2. Fill in all the data from your app into the auth providers fields
3. Login through your server:

```javascript

export const actions: Actions = {
  login: async ({ request, locals, url, cookies }) => {
    const authMethods = await locals.pb.collection("users").listAuthMethods();
    const provider = authMethods.authProviders.find(
      (prov) => prov.name == url.searchParams.get("provider")
    );

    // check if http or https and set host accordingly
    let host = url.host;
    if (host.includes("localhost")) {
        host = "http://" + host;
    } else {
        host = "https://" + host;
    }
    console.log(host);
    const redirectUrl = host + "/redirect";
    if (provider) {
      cookies.set("provider", JSON.stringify(provider));
      throw redirect(303, provider.authUrl + redirectUrl);
    }
  },
};

```

In redirect:

```javascript
import { redirect } from "@sveltejs/kit";
import PocketBase from "pocketbase";

/** @type {import('./$types').PageServerLoad} */
export async function load({ params, locals, cookies, url }) {
    console.log("server load")
    const provider = JSON.parse(cookies.get("provider"));

    let host = url.host;
    if (host.includes("localhost")) {
        host = "http://" + host;
    } else {
        host = "https://" + host;
    }
    
    const redirectUrl = host + "/redirect";
    
    if (provider.state !== url.searchParams.get('state')) {
        console.log("State parameters don't match.");
        return { error: "State parameters don't match." }
    }
    const authData = await locals.pb.collection('users').authWithOAuth2(
        provider.name,
        url.searchParams.get('code'),
        provider.codeVerifier,
        redirectUrl,
        // pass optional user create data
        {
            emailVisibility: false,
        }
    )
    console.log("Auth data: ", authData)
    if (locals.pb.authStore.isValid) {
        cookies.set(locals.pb.authStore.exportToCookie());
    }

    return {
        isValid: locals.pb.authStore.isValid
    }

}

```

The error seems to be that the auth flow doesn't return a valid email (it's blank). In the error logs:

```json
{
  "errorDetails": "email: cannot be blank.",
  "errorMessage": "Failed to authenticate."
}

```

In Microsoft, I even went overboard with the settings, but still no email

<img width="706" alt="image" src="https://user-images.githubusercontent.com/63471891/228193881-95f19911-0c44-4eec-89ee-86e4c9978b4a.png">

Has anyone managed to use Microsoft auth and can help here?

**Comment by Artur-Galstyan** [comment]
I see, removing the requirement did indeed allow me to login. However, the email field is now blank. Is there no way to also add the email? Other login providers such as Google and Discord provide them automatically.

**Comment by ganigeorgiev** [comment]
This is up to the provider. By default we request the minimal `User.Read` scope.

Do you have a `mail` field in the `meta.rawUser` auth response?

**Comment by Artur-Galstyan** [comment]
Thanks for the hint. Upon checking the authdata, I saw this:

```
rawUser: {
      '@odata.context': 'https://graph.microsoft.com/v1.0/$metadata#users/$entity',
      businessPhones: [],
      displayName: '...',
      givenName: '...',
      id: 'bef24d31008f6acd',
      jobTitle: null,
      mail: null,
      mobilePhone: null,
      officeLocation: null,
      preferredLanguage: null,
      surname: '...',
      userPrincipalName: 'blablub@outlook.de'
    },
```

This means, after logging in, I have to take the userPrincipalName and insert it into the email field after logging in. 


Either, there is some configuration I'm missing in Microsoft Azure, or this seems a bit strange to have to change the users collection to accommodate Microsoft. Is this the intended way?

**Comment by ganigeorgiev** [comment]
> Is this the intended way?

No. `userPrincipalName` seems to be used as some sort of a username.

We need the `mail` field to be returned so that we can assign it during user creation.

I'm no sure why in your case is empty. Maybe it depends on the type of the account (personal vs part of an organization) or it is possible that Microsoft has done some changes to the default scopes.

Optionally, you can specify explicit scopes (not just `User.Read`) by changing the query parameters of the signin url link, something like

```js
const url = new URL(provider.AuthUrl + redirectUrl);
const params = url.searchParams;
params.set("scope", "User.Read Mail.Read"); // by spec must be space separated
url.search = params.toString();
const authUrl = url.toString();
throw redirect(303, authUrl);
```

But in any case, I don't think it is related to the SDK. If you are not able to resolve the issue, feel free to let me know and I'll try to create a trial microsoft account to test it later.

**Comment by ganigeorgiev** [comment]
As a side-note, also please note that there is currently a limitation on the email change flow when the user was created with OAuth2 (you can find more in https://github.com/orgs/pocketbase/projects/2?pane=issue&itemId=22401932). This eventually will be fixed (_or at least clearly documented in case a suitable solution is not found_) in v0.15 or v0.16 release.

**Comment by jkdoshi** [comment]
Just got Oauth2 with Microsoft fully working (including getting user's email), so I wanted post an update here.

I had to make a ton of changes to my application configuration on MS side:

1. Register your app with Azure Active Directory as "external" app.
2. Use the https://mydomain.com/api/oauth2-redirect as the redirect URI
3. In order to get user's email, you must register with Microsoft Partner Network (MPN) and enter your MPN id under "Branding & properties". They will also require you to add 2FA to your account.
4. Under "API permissions" add "email" in addition to "User.Read"
5. Now go back to Pocketbase and make sure you use "client id" (not secret id), the secret, https://login.microsoftonline.com/<tenant-id>/oauth2/v2.0/authorize and  https://login.microsoftonline.com/<tenant-id>/oauth2/v2.0/token while creating Auth Provider for Microsoft.

Hopefully, if you get all the incantations right, your MS Oauth2 Provider _might_ just work - including "email" field for your user. Good luck!

![image](https://user-images.githubusercontent.com/2412869/233819502-448980b9-07e9-445e-a89d-fbcae5b3b578.png)

![image](https://user-images.githubusercontent.com/2412869/233819445-69910287-6e8b-457a-93e9-56be994a0264.png)


![image](https://user-images.githubusercontent.com/2412869/233819414-71e3fc11-4539-42ff-a383-c143efd06d22.png)
