### ISSUE TITLE
Issues when deploying to a Cloudflare Worker

### ISSUE THREAD

**Issue by kevmodrome** [pocketbase/js-sdk#18]
Running into issues trying to the SDK and SvelteKit when using the cloudflare-adapter. This is the error I'm running into: `The 'mode' field on 'RequestInitializerDict' is not implemented.`. It does look like this is a CF specific issue.

An issue from the [aws-sdk repo](https://github.com/aws/aws-sdk-js-v3/issues/1165).

**Comment by ganigeorgiev** [comment]
Thanks for reporting it.

I am ok with removing it, but that may break something because we are using `fetch()` with a url argument + additional options config and not with the `Request()` object, so the defaults may be different.

I'll need to investigate this a little further.

**Comment by ganigeorgiev** [comment]
@kevmodrome It looks like that the default `mode` indeed matches with the explicitly stated one, even when using fetch in the `fetch(url, options)` form, so it should be safe to be removed. Please test it with v0.2.2 release.

_In the future I'll consider also adding an optional constructor argument to allow users to specify custom fetch configuration because googling the issue it seems that the `mode` is not the only option that cloudflare doesn't support (there are reports also for `cache`, `referrer`, etc.)._

**Comment by kevmodrome** [comment]
Can confirm that it works! Thanks for the quick fix!
