### ISSUE TITLE
Check if email exist in `users`

### ISSUE THREAD

**Issue by jacksonsophat** [pocketbase/js-sdk#186]
I wanna check if an email exists in the `users` but I always get a 404 even the email exits

` try {
            const checkEmail = await pb.collection('users').getFirstListItem('email = "jackson@email.com"')
            console.log('Exist')
        } catch (err) {
            console.log(err)
            console.log(err.status) //404
        }`

Thank you for helping!

**Comment by ganigeorgiev** [comment]
You can search other users by email only if:
- you are authenticated as admin OR
- your request satisfies the List API rule of your auth collection AND the users `emailVisiblity` flag is `true` (aka. their email is marked "public").

If the purpose of the email search is to check whether a user exist before creating, then this is not necessary, since the `create()` handler have a built-in validator and will thrown an error if a user with the same email exists.

**Comment by jacksonsophat** [comment]
It's a user authentication. I want to the user to be able update email using `.requestEmailChange()`, but I wanna check first if that email exits. 
Where can I set `emailVisiblity` flag is `true`?

**Comment by ganigeorgiev** [comment]
> Where can I set emailVisiblity flag is true?

You can set it as part of the user create/update data OR change it from the Admin UI:
![email_public_screenshot](https://i.imgur.com/hcw3eWa.png)

>  I want to the user to be able update email using .requestEmailChange(), but I wanna check first if that email exits.

**You don't have to manually check for duplicated email. There is built-in validator that will do that for you.**

**Comment by jacksonsophat** [comment]
**There is built-in validator that will do that for you**
Then thank you!! Really appreciate you answering my questions!
