### ISSUE TITLE
select specific fields

### ISSUE THREAD

**Issue by itsgoofer** [pocketbase/js-sdk#187]
Is there a way to `select` only specific fields in a collection when retrieving a list? For example when listing the `users` collection I would like to retrieve only the `email` field.

Thanks.

**Comment by ganigeorgiev** [comment]
At the moment it is not possible without creating a separate View collection with a subset of the felds you want to return.

It is in the [roadmap](https://github.com/orgs/pocketbase/projects/2?pane=issue&itemId=16153865) and will be added in the near future.

**Comment by jorgeqscholz** [comment]
Hi @ganigeorgiev 

I have question regarding this feature. 
Does the `?fields=field1,field2` filter perform an analogous `SELECT field1, field2` filter in the SQL query? Because looking at the Logs section of the Admin UI it seems that it is doing a `SELECT *` query instead, and THEN filtering out the actual requested fields.

I mention this because I've noted some queries taking longer than others if the rows have more data in them (for example, image files), even if I am not selecting those columns.

I hope my question is clear! Thanks for your work!

**Comment by ganigeorgiev** [comment]
> Does the ?fields=field1,field2 filter perform an analogous SELECT field1, field2 filter in the SQL query? 

No. The `fields` query parameter operates on the result.

> I mention this because I've noted some queries taking longer than others if the rows have more data in them (for example, image files), even if I am not selecting those columns.

While the size of the data that is stored in a single record matters, the size of the uploaded files shouldn't matter for the query execution because we store in the database only the related files name (aka. essentially what is returned in the record json response). If you have a performance issues feel free to create a new Q&A discussion with clear steps to reproduce it and I will try to investigate it but there is no option to limit the select fields for the builtin CRUD endpoints if that's what you are trying to do.

You can create a custom route and perform the DB query manually or define a [View collection](https://pocketbase.io/docs/collections/#view-collection) with a subset of the fields you want to select.
