### ISSUE TITLE
Refresh Strategy

### ISSUE THREAD

**Issue by simon-lund** [pocketbase/js-sdk#201]
I wonder when I have to refresh auth of a user.

Is there an auto-refresh mechanism built in?
Or do I have to use authRefresh() to refresh a user's auth?

If so how can I determine if it's time to refresh?

Thx, 
Simon

**Comment by ganigeorgiev** [comment]
> Is there an auto-refresh mechanism built in?

No, but you can subscribe to realtime changes to your `users` collection if you just want to listen to changes of the user fields.

---

> Or do I have to use authRefresh() to refresh a user's auth?

Yes. `authRefresh()` returns a new token with renewed `exp` claim and the latest user data.

---

> If so how can I determine if it's time to refresh?

It depends where it is used.

If your application is entirely client-side (eg. SPA) I personally would call `authRefresh()` on every page load/refresh when `pb.authStore.isValid` to ensure that the `authStore.model` has the latest user data.

If your application sends requests to PocketBase server-side (eg. SSR) then it may be a good idea to call `authRefresh()` on every request when `pb.authStore.isValid` to validate the loaded store token as shown in the [SSR integration examples](https://github.com/pocketbase/js-sdk#ssr-integration).

Alternatively, you can combine the above + checking the `exp` claim of the token payload so that you call `authRefreh()` with some threshold only before the token is about to expire. For example:

```js
import PocketBase, { isTokenExpired } from "pocketbase"; 

const pb = new PocketBase(...)

...

const expireThreshold = 1800; // 30min

if (isTokenExpired(pb.authStore.token, expireThreshold)) { // is about to expire in 30 minutes
    await pb.collection("users").authRefresh();
}
```

**Comment by simon-lund** [comment]
Hello, 

thank you very much. I am using Remix (SSR) and currently I am refreshing on every request.
I wasn't sure if this would create unnecessary overhead.

Best
Simon
