### ISSUE TITLE
Typings of a RecordAuthResponse<Record>

### ISSUE THREAD

**Issue by Fractal-Tess** [pocketbase/js-sdk#206]
Hey there,

Please correct me if I'm wrong, but currently, I do not think there is a way for us to make the `model` property on the `pb.authStore` to be customly typed. 

Is this intended by design or do you have some other plans in mind?

**Comment by ganigeorgiev** [comment]
`pb.authStore.model` has the union type `Record|Admin|null` because it can be any of the listed 3 types.

Additionally, `pb.authStore.model` is a getter and as far as I know TS doesn't allow specifying a generic type on accessor member (aka. if we want to allow a `<T>` we'll have to convert it to a method).

One workaround could be to use type assertion (eg. `pb.authStore.model as SomeInterface`).

If you think that the above can be improved, feel free to let me know and I'll consider it during the planned JS SDK refactoring.

**Comment by Fractal-Tess** [comment]
> One workaround could be to use type assertion (eg. pb.authStore.model as SomeInterface).

I feel like doing such type assertions could be avoided if a generic could be used instead.
Also, positive that you need to assert it to `unknown` first before you can use another type, like so - `pb.authStore.model as unknown as SomeInterface`.

One approach would be to use the `<T>` generic entry point for this model would be on the base `PocketBase` class.
But the drawback here is that we are assuming the user will only authenticate against a single user table, so I think this is a no-go.

I think this only leaves the option to pass a `<T>` generic to the 4 auth methods on the `pb.collection('something')` where that `<T>` would dictate the shape of the returned record.

**Comment by ganigeorgiev** [comment]
> I think this only leaves the option to pass a <T> generic to the 4 auth methods on the pb.collection('something') where that <T> would dictate the shape of the returned record.

The auth methods already support specifying the shape of the returned model (eg. `pb.collection("example").authWithPassword<YourInterface>(...)`), but the generic applies only for the returned data and doesn't affect `pb.authStore.model` which always as declaration the `Record|Admin|null` union type.

_With the planned refactoring I'll consider adding a helper method like `pb.authStore.modelAs<T>(): T|null`._
