### ISSUE TITLE
Feature request: significantly improve Pocketbase + Sveltekit documentation

### ISSUE THREAD

**Issue by joaovbezerra1990** [pocketbase/js-sdk#213]
First congratulations on the idea and execution, brilliant work.

Second, I am having serious trouble trying to integrate Pocketbase + Sveltekit, I believe a more complete example would go a long way. thanks a lot

**Comment by ganigeorgiev** [comment]
I'm not sure how to improve it as the integration will depend on what your application is doing, what SvelteKit adapter you are using, etc.

If you have anything particular in mind, please elaborate what areas did you find difficult to work with and I will try to provide more details but there are no plans to add dedicated guides for working with SvelteKit (or other framework) as it will be too hard to maintain since the JS space changes too quickly.

Users contributions are also welcomed _(the [site documentation](https://github.com/pocketbase/site) will change in the near future with the upcoming v0.17.0 release)_.

**Comment by joaovbezerra1990** [comment]
Thanks for the very quick reply!
You are right, the issue was on my side, I had previously configured a pocketbase server, logged in using it, then created another server and didn't clear cookies.
Spent 4 hours trying to find the issue, then tested chrome and it worked.
I am new to Svelte/Sveltekit, as the other files are complete/correct, I would only add the following to the documentation, as it could save non experienced people some time (my case).

many thanks, keep up the good work!!

login/+page.svelte (sample) 

<script>
  import { goto } from '$app/navigation';
  
  let email = "";
  let password = "";
  
  async function handleSubmit() {
    const response = await fetch('/login', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ email, password }),
    });
    
  
    if (response.ok) {
      goto('/secured');
    } else {
      // Handle login error...
    }
  }
</script>

<h1>Login Page</h1>
  
  <form on:submit|preventDefault={handleSubmit}>
    <label for="username">email:</label><br>
    <input type="text" id="email" bind:value={email} required><br>
    <label for="password">Password:</label><br>
    <input type="password" id="password" bind:value={password} required><br>
    <input type="submit" value="Login">
  </form>
