### ISSUE TITLE
By default, records queried in parallel get cancelled except last one 

### ISSUE THREAD

**Issue by kennethklee** [pocketbase/js-sdk#22]
This is purely opinion -- defaulting to auto cancel every request is unexpected behavior.

Not knowing this, I spent hours debugging my own code before ending up in the pocketbase JS SDK. Learnt to set `$autoCancel` to `false` in every call or use `$cancelKeys` in every request to prevent future issues. 

My use case is a user query in a svelte store init, alongside a page with another user query.

Practically, I see this useful to debounce multiple requests, but there are few places this would apply (i.e. autocomplete search).

Consider defaulting `$autoCancel` to `false`?

**Comment by ganigeorgiev** [comment]
Only duplicated pending requests will get auto cancelled.

Although I can understand why this may not be expected by everyone, in my opinion, it is a lot better to be enabled by default because **it could show and prevent reactivity asynchronous bugs in your application**.

For example, consider a counter function that updates a local state and send request to your PocketBase server on each click:

```js
let myItems = [];

async function onClick() {
    client.records.getList("clicks").then((result) => {
        myItems = result.items;
    });
}


onClick();
onClick();
```

There is no guarantee whether the first or the second `onClick` call will finish last and you may end updating `myItems` incorrectly.

I don't think changing the default to `false` is a good idea since this may introduce bugs in existing user land code.
At the end, when you want to completely disable the auto cancellation behavior, you could always provide a `beforeSend` function and delete the `reqConfig.signal` instance (internally we are using the [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController)):

```js
client.beforeSend = function (url, reqConfig) {
    delete reqConfig.signal;

    return reqConfig;
};
```

_I'll consider documenting it better in the README._

**Comment by hood** [comment]
Wow, so lucky to have found this issue right here. Was experimenting with PocketBase at work with some colleagues, and randomly 404 were being spammed at us for no apparent reason... I was about to ditch PocketBase until I found this! 
*Please* make this explicitly configurable, and disabled by default!

**Comment by ganigeorgiev** [comment]
@hood Auto cancelled request shouldn't result in 404 (`ClientResponseError.status` should be 0 in this case).

I'll add an option in the next release to allow users to disable it more easily (eg. `client.autoCancellation(false)`), but I'm not planning to change the default behavior because the autocancellation helps finding hidden async bugs in user land code (especially if you are using `useEffect` or similar).
