### ISSUE TITLE
AuthStore documentation (README.md)

### ISSUE THREAD

**Issue by felix-schindler** [pocketbase/js-sdk#23]
There are a few mistakes in the AuthStore documentation in the README.md file.

The actual type of model is `User | Admin | {}`. While I'm here I'd also like to ask why it's an empty object and not `undefined`, as it's much harder to work with an empty object.

https://github.com/pocketbase/js-sdk/blob/13c31d8a6f8a2415e14e6e99f8cf3bc407c0ea7a/README.md?plain=1#L169

Also, in the methods there is no `onChange()` method, while 10 lines below it says there is a `client.authStore.onChange()` method.

https://github.com/pocketbase/js-sdk/blob/13c31d8a6f8a2415e14e6e99f8cf3bc407c0ea7a/README.md?plain=1#L172

**Comment by ganigeorgiev** [comment]
Thanks, I'll update later this evening the README.

> While I'm here I'd also like to ask why it's an empty object and not `undefined`

This is just a personal preference of mine since I find it more convenient when calling for example `client.autStore.model.id` (aka. you don't have to rely on the env specific optional chaining operator support). I may consider updating it in the future to `User|Admin|null` but I'll have to think a little more on this since it will be a breaking change.

The `onChange()` method is not part of the AuthStore interface (since it was introduced in later version) and it is available only if you extend the [BaseAuthStore](https://github.com/pocketbase/js-sdk/blob/master/src/stores/BaseAuthStore.ts) abstract model.

**Comment by ganigeorgiev** [comment]
I've update the README in `master` to reflect the proper AuthStore model type (the npm documentation will be updated with the next v0.5.0 release I'm planning sometime next week).

Although we haven't reached a stable v1.0.0 version yet, for now it will remain as `User|Admin|{}` to avoid unnecessary breaking existing user land code, but if other developers also ended up complaining about this, I may reconsider changing `{}` to `null`.

If you want to check whether your `authStore` instance has a "valid" authenticated model, use the `isValid` getter or check if the model has a non-empty `id` prop.

**Comment by ganigeorgiev** [comment]
@felix-schindler Just to let you know that with [v0.6.0 SDK release](https://github.com/pocketbase/js-sdk/releases/tag/v0.6.0), the model definition was changed from `User|Admin|{}` to `User|Admin|null`.

_It turned out that the usage of `{}` depends too much on the TS configuration, and in some more strict environments `{}` has different access capabilities than `{ [key: string]: any }`._
