### ISSUE TITLE
RecordSubscription<Record> action=create doesn't have unknown data fields

### ISSUE THREAD

**Issue by iMro0t** [pocketbase/js-sdk#231]
```javascript
pb.collection("carousel").subscribe("*", (data) => {
   console.log(data.action, data.record)
})
```

in http response it has unknown fields but missing in `data.record`

**Comment by ganigeorgiev** [comment]
I'm not sure that I understand what do you mean.

The Record model is not generated!, aka. meaning that your specific collection fields will not be part of the model TS declaration and will be a dynamic prop. The dynamic part is allowed by the `[key: string]: any` declaration in [BaseModel](https://github.com/pocketbase/js-sdk/blob/master/src/models/utils/BaseModel.ts#L2).

If that's not what you mean, please elaborate and I'll investigate it.

_Side-note: please also check https://github.com/pocketbase/pocketbase/discussions/3134._

**Comment by ganigeorgiev** [comment]
If by "unknown fields" you mean custom and non-collection fields set server-side in a Go/JS app hook and enabled with `record.UnknownData(true)` - then No, they will not appear in the realtime event since we always create a "clean copy" of the record state before broadcasting it without expand or any other custom data (_this is because we don't know if the clients have permission to view them_).
