### ISSUE TITLE
Event when signin is cancelled/popup is closed

### ISSUE THREAD

**Issue by daanschenkel** [pocketbase/js-sdk#233]
Hi! Im trying to make it so when you initialize pocketbase auth with oauth it disables all the login buttons and dims the page slightly, i however cant seem to find a way to check when the popup is closed/auth is cancelled. Can this be implemented or does this already exist?

**Comment by ganigeorgiev** [comment]
Trying to detect a popup close event turned out to be more troublesome than I anticipated, even with the `setInterval` check.

On each redirect or any url change a new browser context is created, marking the previously created `Window` instance as `closed`, aka.:

```js
const win = window.open("http://google.com")

// ... wait the popup page to load and to auto redirect to the HTTPS version ...

console.log(win.closed) // -> will return "true" even though the browser window is still open
```

So in other words - there is no reliable way to detect it, since there is no guarantee to work with all OAuth2 providers because they could have internal redirects.

If you really need it, my recommendation in your case would be when the user clicks on the "Login with ..." button, to show an overlay on top of the form that will indicate that an auth process has started and add a "Retry" button somewhere that will remove the overlay and will allow the user to start a new auth process (_even though the previous may not be completed_).
