### ISSUE TITLE
Error when using the OAuth2 all-in-one integration

### ISSUE THREAD

**Issue by gdrose** [pocketbase/js-sdk#236]
I alredy had the OAuth2 working a few months ago in my platform using the Manual Code Exchange method but just now I saw the all-in-one so I was switching with it when I caught this error:

From the pocketbase debug logs:
`2023/08/31 06:53:30 code=400, message=Unmarshal type error: expected=string, got=object, field=provider, offset=13, internal=json: cannot unmarshal object into Go struct field RecordOAuth2Login.provider of type string`

I litterally just copied and pasted the code from the documentation:

```
<script>
	export let data;
	import PocketBase from 'pocketbase';
	const pb = new PocketBase(data.pb);

	async function login() {
		await pb.collection('users').authWithOAuth2({ provider: 'google' });
	}
</script>

<button on:click={login}>singin</button>
```
I am using svelteKit so I also tried using the function in the +page.server.js instead of the +page.svelte (code above) but it throws the same error. Is it my fault?

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce it. I suspect that you are using an older PocketBase executable or JS SDK version.

Note that the OAuth2 "all-in-one" oauth2 code is supported with PocketBase executable v0.15+ and JS SDK v0.14+.

Additionally, keep in mind that the "all-in-one" call will not work in entire server-side context because it needs to open a browser url and maintain a persistent/realtime connection.

If the versions of the executable or the JS SDK is not the cause of the issue, please create a **minimal** reproducible repo and I'll try to investigate it further.

**Comment by gdrose** [comment]
Thank you for the prompt response, I was having problems with a previous migration. I'm now getting this error in the console though:

`Cross-Origin-Opener-Policy policy would block the window.close call`

**Comment by ganigeorgiev** [comment]
I don't think we add the `Cross-Origin-Opener-Policy` header.

If you have a reverse proxy (nginx, caddy, etc.), double check its configuration.

It is possible to be also something provider specific that may need adjustments in the OAuth2 vendor app.

It could be also caused by a browser extension, I'm not sure.

Testing locally with PocketBase v0.17.7 and JS SDK v0.17.3 I'm not able to reproduce it.

If you are still not able to resolve the issue, please try to provide some more details about your setup (where and how PocketBase is deployed, what versions of the executable and JS SDK do you use, how do you interact with PocketBase, etc.) and ideally some reproducible steps.

**Comment by gdrose** [comment]
I'm running:
v0.17.7 for Windows (running locally)
pocketbase@0.17.3 (with sveltekit)

this is currently my code in a +page.svelte
```
<script>
	export let data;
	import PocketBase from 'pocketbase';

	async function login() {
		const pb = new PocketBase(data.pb);

		const answer = await pb.collection('users').authWithOAuth2({ provider: 'google' });
		await pb.collection('users').update(pb.authStore.model.id, { name: answer.meta.name }); // It works

		console.log(pb.authStore.isValid); // true
		console.log(pb.authStore.token); // ey.....
		console.log(pb.authStore.model.id); // id
	}
</script>

<button on:click={login}>singin</button>
```

I still get the error in the console but somehow it creates the user and the authStore is valid and it seems like everything went well but the user is not logged in. Even with the authStore working the cookie is not set so it's not loaded.

**Comment by ganigeorgiev** [comment]
I think you are confusing the server-side client with the client-side.

This is a common misunderstanding but I really don't know how to explain it better (there are at lease dozens similar questions in the main repo discussion).

As far as I understand, the above is executed entirely client-side and there are no cookies used (there are also no interaction with the node server).

Please keep in mind that PocketBase doesn't really use or need cookies.
The cookies are used only as a "transport mechanism" between the client and your node server.

If you want a mixed access to the PocketBase server (both from node and browser) and to maintain the same user auth state, then you can check the browser client example in https://github.com/pocketbase/pocketbase/discussions/3111#discussioncomment-6697302.

**Comment by gdrose** [comment]
Thank you! I'm just curious, how I should pass the document safely from the client-side context to the server-side one? 
```
// browserclient.js
import PocketBase from "pocketbase";

const pb = new PocketBase(url);

pb.authStore.loadFromCookie(document.cookie) <--- How is the document referenced/defined here?

pb.authStore.onChange(() => {
  document.cookie = pb.authStore.exportToCookie({ httpOnly: false }); <--- ?
});

export default pb; // it is safe to be global in this case
```

if the client-side looks like this:

```
<script>
        import pb from "./browserclient.js"

	async function login() {
		await pb.collection('users').authWithOAuth2({ provider: 'google' });
	}
</script>

<button on:click={login}>singin</button>
```

It wouldn't be easier to just trigger an action on the server side or hit an endpoint? Just asking, sorry if the questions are redundant or "stupid" 

P.S.: all of the code above is just copy-paste of the discussion you linked me.

**Comment by ganigeorgiev** [comment]
It is safe to use a global client-side SDK instance because the client is only 1 (aka. the browser).

When using SSR it is NOT safe to use a single global instance for user authentication because multiple clients (browsers) are sending requests to a single point (the node server) and each request will write over the same `pb.authStore` state.

>  How is the document referenced/defined here?

I don't understand what do you mean. `document.cookie` contains the raw cookie string. It is automatically populated if the node server has set cookies in the response. 

`httpOnly` needs to be `false` to allow access to the cookie for client-side JavaScript code (it needs to be set to `false` also from the server-side).

---


I'm sorry, I really don't know how to explain it better. A lot of devs jump straight into complex SSR frameworks and expect a one-liner but I don't think this can be done.
**If you use node SSR you no longer have "just frontend".** You effectively have to maintain 2 backends and how your users will interact with these backends and how you'll sync their state depend on your use case and the desired flow. There is no universal answer to this.

If you want my straight recommendation - don't use SSR if you are not sure why you need it.
I'll consider in the upcoming weeks to update the docs and create a post with some examples and recommended patterns for client-side integrations.

**Comment by gdrose** [comment]
My case study needs SSR that's why I'm using it (even though I'm not a big fan). The main point is that I really want to optimize the way I'm implementing pocketbase into my project that's why I'm always wondering the best approach.

Regarding the `document.cookie` I know what it contains but it is simply not defined:

```
Error when evaluating SSR module /src/lib/browserclient.js:
|- ReferenceError: document is not defined
```
`httpOnly` is false.

By the way, I really appreciate the support 😄

**Comment by ganigeorgiev** [comment]
`document`, `windows`, etc. are supported only client-side.
I guess it depends on the SvelteKit adapter you use, but the general suggested solution seems to be to wrap the client-side code in a `browser` check or import the code in the `onMount` hook (see https://kit.svelte.dev/docs/faq#how-do-i-use-x-with-sveltekit-how-do-i-use-a-client-side-only-library-that-depends-on-document-or-window).

**Comment by gdrose** [comment]
To be honest, even after wrapping everything still the document is not shared between the client-side (+page.svelte) and the server one (browserclient.js) so it still throws the reference error.

I just went with this approach:

```
<script>
	import PocketBase from 'pocketbase';
        import { browser } from '$app/environment';

	async function login() {
		if (browser) {
			const pb = new PocketBase(url);

			pb.authStore.loadFromCookie(document.cookie);

			pb.authStore.onChange(() => {
				document.cookie = pb.authStore.exportToCookie({ httpOnly: false });
			});

			const answer = await pb.collection('users').authWithOAuth2({ provider: 'google' });
			await pb.collection('users').update(pb.authStore.model.id, { name: answer.meta.name });
		}
	}
</script>

<button on:click={login}>singin</button>
```
