### ISSUE TITLE
requestPasswordReset is true, but doesn't send reset email.

### ISSUE THREAD

**Issue by alef0gli** [pocketbase/js-sdk#248]
$lib/pocketbase.js
```
import PocketBase from 'pocketbase';

export const pb = new PocketBase("http://127.0.0.1:8090");
```

+page.server.js
```
import { pb } from '$lib/pocketbase';

/** @type {import('./$types').Actions} */
export const actions = {
	reset: async () => {
		let email = 'test@example.com';
		let reset = await pb.collection('users').requestPasswordReset(email);
		console.log(reset);
	}
};
```

Expected Behavior:
When requestPasswordReset is called with a valid email address, it should send a password reset email to the specified user. The email should contain instructions on how to reset the password.

Actual Behavior:
When requestPasswordReset is called with a valid email address, no reset email is being sent and the console log prints reset = true

**Comment by ganigeorgiev** [comment]
This is intentional to avoid user enumerations.
The request password will always return a success response no matter whether a user with the specified email exists or the email was successfully sent.

Additionally, internally we also have a very rudimentary flood protection that will skip the email send if the previous email was sent < ~2 minutes.

For more detailed errors you can start the PocketBase executable with `--debug` and/or check the request logs in the _Admin UI > Logs_.

**Comment by ganigeorgiev** [comment]
Also note that by default PocketBase uses the unix `sendmail` command (if availabel) which is not very reliable and it is recommend to enable the SMTP setting when sending emails.

You can also test the email send functionality from the _Admin UI > Settings > Mail settings_.

For a test SMTP server I often use [mailtrap.io](https://mailtrap.io/email-sandbox/) (_the have free option and doesn't require providing billing details_).
