### ISSUE TITLE
Global Typescript definition

### ISSUE THREAD

**Issue by patmood** [pocketbase/js-sdk#254]
The global typescript definition is an amazing addition, thank you! It has already been added to https://github.com/patmood/pocketbase-typegen

I have a suggestion to improve the return type:

Here's the example from the docs
```
interface Task {
  id:   string;
  name: string;
}

interface TypedPocketBase extends PocketBase {
  collection(idOrName: 'tasks'): RecordService<Task>
}

const pb = new PocketBase("http://127.0.0.1:8090") as TypedPocketBase;

pb.collection('tasks').getOne("RECORD_ID") // -> results in Promise<Task>
```

I think the results should automatically extend `RecordModel` instead of just `Task`, so it includes fields like `id`, `expand`, `created`,`updated` etc

The reason the user can't manually do this in the `TypedPocketBase` interface is because that basic `Task` type is required for create/update methods. 

Is this able to be inferred by the sdk?

**Comment by ganigeorgiev** [comment]
I'm sorry, I'm not sure I follow what actually is the issue here.

If users want to extend `RecordModel` then they can do that on their own, it is not much different then the explicit generic `getOne<Task>()`.

**Comment by patmood** [comment]
When using global type definition `create()` expects the same `Task` type that is returned by `getOne`, but they are not the same.

`getOne` returns extra fields like id/collectionId/collectionName/created/updated/expand.

This isn't an issue with explicit generics because you can specify different types for each method (`pocketbase-typegen` generates a `Task` and a `TaskResponse` to handle this).

**Comment by ganigeorgiev** [comment]
`Task` just describes a subset of common fields the user want to access. It doesn't perform cast or anything like that. If users want TS to not complain when accessing `collectionId`, `collectionName`, etc. then they can define it in the interface (or extends it on their own via the `RecordModel`). This is exactly the same as the individual methods generic, there is really no difference. The global generic just sets a default type for the generic arguments (previously the default was hardcoded to `RecordModel`).

Also note that `getOne`, `getList`, `create`, etc. methods all can return custom subset of fields when the `fields` parameter is set.

> create() expects the same Task type that is returned by getOne

I don't understand this. I haven't personally used [pocketbase-typegen] so I'm not sure if this is something specific to it, but the accepted body argument for the `create` method in the JS SDK should be something like: `{[key:string]:any}|FormData` because technically it can be anything (including custom data that is submitted only to be checked in the API rules via `@request.data.*`).

In any case I don't think this is an issue with the SDK, or at least I don't understand the root of the problem. If you think that something can be changed to make it easier integrating with your package, feel free to open a PR with the suggestion and I'll have a look.
