### ISSUE TITLE
[Feature]: authWithOAuth2 support AbortSignal

### ISSUE THREAD

**Issue by shynome** [pocketbase/js-sdk#265]

**Comment by ganigeorgiev** [comment]
Please don't open issues without description. Could you elaborate what is your use case?

**Comment by ganigeorgiev** [comment]
If you are trying to cancel a pending `authWithOAuth2()` call I guess we can introduce a `requestKey` support similar to the other SDK methods, which will allow cancelling with `pb.cancelRequest(requestKey)`.

The problem with the "all-in-one" `authWithOAuth2()` call is that it performs 3 different requests - `listAuthMethods`, start a realtime subscription and finally call to the `authWithOAuth2Code()` method. It is doable but requires some more thinking.

**Comment by ganigeorgiev** [comment]
Under the hood the builtin request cancellation is managed managed by a `AbortController`.
There are no plans for now to pass `AbortController`/`AbortController.signal` as argument because it will be inconsistent with the other APIs and internal implementation may change in the future.

As mentioned earlier, I'll consider supporting passing `requestKey` to the "all-in-one" `authWithOAuth2()` method but I'll have to think a little more on it and for now remains a low priority.

**Comment by shynome** [comment]
Thanks for your reply, I had implement it by myself, so it will not  block me.

`requestKey` is fine, but it need export `cancelRequestKey` function, let user can muanal control cancel it

**Comment by ganigeorgiev** [comment]
Support for cancelling the OAuth2 flow using `requestKey` is added in [v0.21.4 release](https://github.com/pocketbase/js-sdk/releases/tag/v0.21.4).

**Comment by shynome** [comment]
`.authWithOAuth2()` don't resolve promise when login window has been closed

**Comment by ganigeorgiev** [comment]
> .authWithOAuth2() don't resolve promise when login window has been closed

This unfortunately is expected because there is no easy way (or at least I couldn't find) how to detect a closed window across different browsers and platforms (see https://github.com/pocketbase/js-sdk/issues/233)

> add: and pb.cancelRequest('oauth-login') don't resolve the promise authWithOAuth({ key: 'oauth-login' })

For the all-in-one flow the cancellation works only during the actual OAuth2 auth call, which is invoked after the redirect from the OAuth2 provider. I'll consider tomorrow to investigate how feasible would be to unsubscribe from the OAuth2 realtime subscription too.

**Comment by ganigeorgiev** [comment]
I've pushed a fix in [v0.26.8](https://github.com/pocketbase/js-sdk/releases/tag/v0.26.8) for the Promise resolving when manually calling `pb.cancelRequest()` _(and on network/server-side realtime disconnect)_.

The popup close detection unfortunately remains unresolved for the time being.

**Comment by shynome** [comment]
Wow, that was fast and really well done. I can delete my glue code now. Thanks! `pb.cancelRequest('oauth-login')`

#233 oh, The popup close detection is harder than I thought.
