### ISSUE TITLE
is there getLastListItem for get Last data

### ISSUE THREAD

**Issue by bobwatcherx** [pocketbase/js-sdk#292]
give me docs link for get last data .

i see you use getFirstListItem() . is there for last data

**Comment by ganigeorgiev** [comment]
You are not entitled to anything. Please don't treat the issue tracker like ChatGPT. I've blocked you once due to spam. Next time will be permanent.

In any case, to fetch the "last" data you can specify a `sort` argument
```js
await pb.collection("example").getFirstListItem("title='something'", {
    sort: "-created" // or some other critetia
})
```

Alternatively, you can always send a `getList(1, 1, { ... })` request (that's what `getFirstListItem` technically does).
