### ISSUE TITLE
Should LocalAuthStore use globalThis.localStorage instead of window.localStorage?

### ISSUE THREAD

**Issue by godmar** [pocketbase/js-sdk#293]
Right now, [`LocalAuthStore.js` tests for `window.localStorage`](https://github.com/pocketbase/js-sdk/blob/master/src/stores/LocalAuthStore.ts#L67) before using `localStorage`.  This means it's not working with, for instance, the [node-localstorage](https://www.npmjs.com/package/node-localstorage) polyfill for node.js because that polyfill [attaches `localStorage` to `global`](https://github.com/lmaccherone/node-localstorage/blob/master/register.js).

Would it be better to use [`globalThis`](https://caniuse.com/?search=globalThis) instead or is there a reason that the implementation requires an actual `window` object?

**Comment by ganigeorgiev** [comment]
No. It is better to remain with `window` as it is safer in case the user uses the library for regular users auth in a server context, eg. JS SSR (see also the [note about Deno](https://github.com/pocketbase/js-sdk?tab=readme-ov-file#localauthstore-default) since the last time I tested there was `window` global object):

> NB! Deno also supports LocalStorage but keep in mind that, unlike in browsers where the client is the only user, by default Deno LocalStorage will be shared by all clients making requests to your server!
