### ISSUE TITLE
Extremly Slow Request

### ISSUE THREAD

**Issue by ValentinKolb** [pocketbase/js-sdk#297]
Hi,

I have a strange situation:

In the API filters for a collection, I use `@collection.` which references the collection itself, among others. It seems that this part is slowing down any List/Search request (a simple `getList(1,10,{})` takes over 10 seconds). However, this only happens if the `@collection.` rule addresses a _large_ amount of records (over 200 or so). For example: `@collection.users.username~'a'` -> Problem, but `@collection.users.username~'y'` -> No problem, fast.
I use multiple `@collection.` joined with `&&`.

Now the strange part: The exact same rule exists for the View Rule, but here the request goes through super fast.

Can I take any steps to debug this issue further? I have enabled '--dev' but that only showed me that the query resulting from getList also went through super fast. The debug logs didn't show the query of the permission system (if there is any?).

Thanks for your help!

**Comment by ganigeorgiev** [comment]
Without some reproducible steps I'm not sure how to help.

Are you sure that you need the `@collection.*` rule in the first place? As mentioned in https://github.com/pocketbase/pocketbase/discussions/4928 it performs a `JOIN` so it could have impact on the perform if not properly used (the same apply if you execute a raw SQL statement).

Do you have custom indexes? If not defined on the correct fields they can also cause performance issue since they may affect what route the query planner will choose (see https://github.com/pocketbase/pocketbase/discussions/3859#discussioncomment-7744045).

If `--dev` shows that the query executes fast, are you sure that the issue is caused by PocketBase and not by something else (rate limits of the deployment environment, issue with inefficient API interactions from other backends like Next.js or SvelteKit, etc.)?

In any case to rule out PocketBase issue you could create a plain `pb_public/index.html` with something like:

```html
<!DOCTYPE html />
<html>
<head>
    <meta charset="utf-8" />
    <title>Test</title>
</head>
<body>
    <script type="module">
        import PocketBase from "https://cdn.jsdelivr.net/gh/pocketbase/js-sdk@master/dist/pocketbase.es.mjs"

        const pb = new PocketBase("http://127.0.0.1:8090");

        // authenticate if necessary
        // (authWithPassword is expected to be slow due to the bcrypt hash verification)
        await pb.collection("user").authWithPassword("test@example.com", "1234567890")

        const records = await pb.collection("example").getList(1, 10)
        console.log(records)
    </script>
</body>
</html>
```

Open your browser, navigate to `http://127.0.0.1:8090` and check the request times in the "Network" console tab.

If you are still not able to identify the culprit, please try to create a **minimal** reproducible repo or at least export your collections configuration as json (_Admin UI > Settings > Export collections_) and I'll try to investigate further but until then there is nothing much I can help with.

**Comment by ganigeorgiev** [comment]
I forgot to mention that custom hooks code could also have impact on the performance, but again without reproducible steps or at least some details it is hard to pinpoint the exact cause.

**Comment by ValentinKolb** [comment]
Thanks for the quick answer!

I could confirm that it wasn't a client-side problem. To clarify: by "the query executed fast" i mean that the sql query for the `getList` was fast, not the network query. I am using custom hooks, but only triggered on an completely different and unrelated collection. Could that still have an impact.

I have put together a miminal example and would be grateful if you would take a look at it.

Maybe for a general explanation. I am building an event management system in which users can create events, an event then has several lists (e.g. tickets or helpers) and each list has time slots. users can then register in these time slots.

I need the `@collection` because all persons who are entered in special lists should also see all other entries for this event. this is necessary, for example, so that the "admission helpers" list can check the tickets, etc. The lists that have such a special role are specified in `event.privilegedLists`.

[pb_schema(3).json](https://github.com/user-attachments/files/15865933/pb_schema.3.json)

**Comment by ganigeorgiev** [comment]
> I could confirm that it wasn't a client-side problem.

I have no way to verify your findings.


> I have put together a miminal example and would be grateful if you would take a look at it.

Where? The above exported json is not enough to reproduce your problem locally. It doesn't contain any information about your custom code, nor details against what collection you are actually executing the request.

If the SQL query executes fast, then I don't see what exactly PocketBase could do result in slow network request in your case.

Couple things based on the provided json:
- You don't need the unique constraint for the users.username as there is already existing one created by default because the username is a system field.
- In the `eventListSlotEntries` collection rule if you are comparing a single value against a multiple relation field you need to specify the field (eg. id) you wan tto check, aka. probably:
  ```js
  @collection.eventListSlotEntries.eventListsSlot.eventList ?= eventListsSlot.eventList.event.privilegedLists
  ```
  should be:
  ```
  @collection.eventListSlotEntries.eventListsSlot.eventList ?= eventListsSlot.eventList.event.privilegedLists.id
  ```

I'm sorry but this is really frustrating for me and I don't want to deal with this type of constant back-and-forth. I consider it lazy and low effort and I'm not going to invest time on a wild goose chase if the user doesn't want to spend time providing a proper reproducible or at least how many records and what requests they send so that I can try to emulate their setup locally (I don't even understand why do you think this is JS SDK related...).

**Comment by ValentinKolb** [comment]
Thanks for the comments regarding the database schema!

It is by no means my intention to take up too much of your time! I am very grateful for your quick and clear answers.
It is difficult for me to create a reproducible example as the problem seems to occur only in very specific cases. I will try to identify them clearly and then get back to you with an executable example.

many thanks
