### ISSUE TITLE
Auto adding query into any options variable

### ISSUE THREAD

**Issue by lixelv** [pocketbase/js-sdk#308]
For some reason, when I'm giving to subscribe function some options variable, It wraps her arguments in query: {}. This is not cool, to find, that your variable was edited, when you just gave it to your function. I've fixed this by replacing options (in func) on JSON.parse(JSON.stringify(options)). May be there are more efficient way, but idk. Here is example:
```ts
let options = {
	sort: '-updated',
	expand: 'allowed,owner'
};

await pb.collection('users').subscribe('*', () => {}, options);

console.log(options);

// options = {
//     "query": {
//         "sort": "-updated",
//         "expand": "allowed,owner"
//     }
// }
```

**Comment by ganigeorgiev** [comment]
I've pushed a minor update in [v0.21.5 release](https://github.com/pocketbase/js-sdk/releases/tag/v0.21.5) to shallow copy the options argument similar to the other methods.

Note that we don't do deep clone because the `options` argument could technically contain user defined functions (e.g. `fetch`) which will require special manual handling. I'll think a little more on it with the refactoring and eventually may create a helper that will call [`structuredClone`](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) + some additional handling for the special cases but for now remains a low priority.
