### ISSUE TITLE
Feature request: async AuthStore implementation

### ISSUE THREAD

**Issue by qysp** [pocketbase/js-sdk#31]
The current `AuthStore` implementation (using the local storage by default) is based on synchronous methods.

However, other storage solutions, e.g. the [Ionic Storage](https://github.com/ionic-team/ionic-storage), only work with asynchronous methods and can therefore not be used. I could also see this being useful in Node.js in case an `AuthStore` is being implemented using a database as storage.

**Comment by ganigeorgiev** [comment]
Hm, I don't think we can have both sync and async support at the same time. The store function declarations will have to be updated to return a `Promise` and things could get really messy in TS environments if we add sypport for a union type.

To be honest, I'm not sure that I see a use case for this. The `AuthStore` just holds the last authenticated token and model and if someone want to store them in a database they can always create a wrapper around the store or just attach a listener with `client.authStore.onChange((token, model) => { ... })`.

Ionic Storage is a generic storage solution and for them it makes sense to have async behavior, because most storage adapters that operates with files usually require it (IndexedDB API for example is async).

Do you have any specific use case for this feature?

**Comment by qysp** [comment]
Yeah, I didn't mean to propose supporting sync and async implementations, that wouldn't really work.

My specific use case would actually be the Ionic Storage since my client uses Ionic in general. So in order to use it right now, I'd basically have to load the auth data before app initialization for auto login and also implement the `client.authStore.onChange((token, model) => { ... })` event listener.
I guess that should also work! :-)

**Comment by ganigeorgiev** [comment]
Loading/Saving the auth data on app initialization and using a listener is the best way to go in this scenario.

Even if we change the store implementation to be async, you still will need some kind of wrapper in order to make it work with the Ionic Storage.
