### ISSUE TITLE
FR: Please include the usage of "fields" in the documentation

### ISSUE THREAD

**Issue by Mashiane** [pocketbase/js-sdk#313]
Hi

On the Web API reference, there is functionality to specify which fields to select from a collection.

I could be wrong, but it does not seem to be documented on the JavaScript SDK docs.

Thanks

**Comment by ganigeorgiev** [comment]
The supported Web API fields are listed both in the Web API reference, as you've noted' and it the API preview section in the Admin UI.

In any case the documentation will change significantly due to the upcoming v0.23.0 release and there is no need to litter the issues tracker or the README with every minor detail.
