### ISSUE TITLE
listauthmethods not returning values

### ISSUE THREAD

**Issue by etcSudoers** [pocketbase/js-sdk#320]
Maybe I am doing it wrong, but when I try to use the .listAuthMethods function I am not seeing the expected values.  Basically an empty object

```
const authMethods = await pb.collection('users').listAuthMethods();
console.log('Available Authentication Methods:', authMethods);
```

The console log does not show any of the values that i have setup:  user and password, and gitea.  Just an empty object.

pocketbase version 0.22.25

![image](https://github.com/user-attachments/assets/fa2077b4-1f98-419a-adf7-56d809e8e958)

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce it. We have automated tests in both the JS SDK and the server-side and they complete successfully. I can also confirm that it works because I'm using it in production with [Presentator](https://presentator.io/).

You can check that:

- there is no cache on meta-framework (e.g. Next.js) or reverse proxy level (nginx, apache, caddy, etc.)
- there is no conflicting Go or JSVM hook that may intercept/change the `listAuthMethods` response
- check the network response in the browser's _Inspect tool > Network_

You can also rule out 3rd party tool misconfiguration by creating a plain `pb_public/index.html` file:

```html
<!DOCTYPE html />
<html>
<head>
    <meta charset="utf-8" />
    <title>Test</title>
</head>
<body>
    <script type="module">
        import PocketBase from "https://cdn.jsdelivr.net/gh/pocketbase/js-sdk@master/dist/pocketbase.es.mjs"

        const pb = new PocketBase("http://127.0.0.1:8090");
        
        const result = await pb.collection("users").listAuthMethods()

        console.log(result);
    </script>
</body>
</html>
```

Open the browser, navigate to `http://127.0.0.1:8090` and check the console output.

If you are still not able to identify the culprit, feel free to provide more details about your setup and a more detailed code sample illustrating the problem and I'll try to have a look at it but as of now there is nothing much I can help you with here.

**Comment by ganigeorgiev** [comment]
If you are using PocketBase v0.22.25, make sure that use a compatible JS SDK version, aka. <= v0.21.5 (if use the JS SDK v0.22.0-rc then this will not work because as mentioned in the [release notes](https://github.com/pocketbase/js-sdk/releases) it is compatible only with PocketBase v0.23.0-rc+).

**Comment by etcSudoers** [comment]
Ah, you are spot on.  I was using the RC.  Just tried with the 0.21.5 and works as expected.

My bad
