### ISSUE TITLE
May i use this api as plain old JavaScript library?

### ISSUE THREAD

**Issue by recoilme** [pocketbase/js-sdk#48]
I am not frontend dev, and don't want to learn typescript, node, react vue or svelte frameworks for making simple request.. Is it possible now? How to get JavaScript source?

**Comment by ganigeorgiev** [comment]
The JavaScript SDK is framework agnostic and there are no depedencies with svelte, vue, react, etc. You can use it even without a webpack/rollup/etc. bundler and directly load the [UMD file from the dist folder](https://github.com/pocketbase/js-sdk/blob/master/dist/pocketbase.umd.js) in your html as shown in the README - https://github.com/pocketbase/js-sdk#browser-manually-via-script-tag.

**Comment by recoilme** [comment]
This method not work for me as provided in readme:
<script src="/path/to/dist/pocketbase.umd.js"></script>
It gave some error about not module defined 

But second method - worked:

```
    <script type="module">
        import PocketBase from '/js/pocketbase.es.mjs'
        const client = new PocketBase('http://127.0.0.1:80');
        const adminData = await client.admins.authViaEmail('t@t.ru', '1234567');
        console.log('New store data:', adminData)
    </script>
```
I add this in router
```
	app.OnBeforeServe().Add(func(e *core.ServeEvent) error {
		e.Router.Static("/js", "web_data/js")
```
And place es.mjs/es.mjs.map in web_data/js
Hope this may help someone..

But compiled javascipt, not readable... And i dont found a way how to fix it...

By my opinion it's hard to understand from readme for beginners

**Comment by ganigeorgiev** [comment]
`pocketbase.es.mjs` is es js module. It practically allows you to use `import/export` in the browser. You can read more in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules.

`pocketbase.umd.js` is a UMD (universal-module-definition) file. It can be loaded like any other js file and it works both in node and in the browser:

```html
<script src="/path/to/pocketbase.umd.js"></script>
<script type="text/javascript">
    const client = new PocketBase('http://127.0.0.1:80');

    async function load() {
        const adminData = await client.admins.authViaEmail('test@example.com', '123456');
        console.log('New store data:', adminData)
    }

    load();
</script>
```
There is no source map file for the umd bundle because it is rarely used, but I'll consider adding it to the build script in the next release.

---

> By my opinion it's hard to understand from readme for beginners

I'm not sure how to simplify it. Suggestions are more than welcomed. Some familiarity with JS is expected from the developers. 
If you are not using PocketBase as a framework, you can directly put your js file in `pb_public` folder next to your executable and everything inside that directory will be available under the url: `https://yourdomain.com/yourfile.js`. Your example implies that you are using PocketBase as framework and I guess your difficulties come with serving static files from the Go backend, right? If that's the case, I'll consider making helper Go functions and show an example how to define a static route.

**Comment by recoilme** [comment]
thank you for clarification!

My suggestions is add more details to readme about using as js.. 

I think if add this example and text in readme (how to use umd.js) - will help to noobs like me in nowadays js (my mistake was in copy/pasting import module in case of umd, but now it's work). My english is poor, thats why i didn't send PR in readme

Second think what i steal don't understand - is how to get not compiled/minified js code? It's very hard to debug minified code, or it's not possible because of typescript?

**Comment by ganigeorgiev** [comment]
> Second think what i steal don't understand - is how to get not compiled/minified js code? It's very hard to debug minified code, or it's not possible because of typescript?

Hm, placing the sourcemap alongside the js file should allow you to debug the unminified code in the browser. If this doesn't work, then probably there is something wrong with our rollup config (_I'll test it tomorrow and will consider adding sourcemap for the umd bundle too_).

**Comment by recoilme** [comment]
And yes, i use it as framework, but difficulties for me come from frontend part and integration with telegram. I add telegram as oauth provider - but hooks are very hard in that way. So i will hook telegram auth via email/password now (any news about 0.8 experimental build?) And some misunderstanding how to use it as js (i try to read svelte docs - but it's hard to learn in one day for me) So i decide go to old good way..

Is sourcemap is  pocketbase.umd.d.ts? i don't provide it, i will try, thanks for your time!

**Comment by ganigeorgiev** [comment]
> any news about 0.8 experimental build?

It will be available soon. Unfortunately I have some work to catch up at the office this days, so I don't have much time left to work on it, but expect a pre-release within the next 2-3 weeks.

---

> is sourcemap is pocketbase.umd.d.ts? 

No, this is the TypeScript types definition file. If you are not using TS you don't need it. The sourcemap is the `*.map` file.

**Comment by jacobcwright** [comment]
I think you might've meant to ping @recoilme
