### ISSUE TITLE
Sveltekit / Node > 16: ClientResponseError 404 Every Time

### ISSUE THREAD

**Issue by timmyjl12** [pocketbase/js-sdk#53]
I am on Windows pocketbase version 0.7.9, npm pocketbase version 0.7.4, and the latest sveltekit. I am using the default example for sveltekit in the readme.

When using node > 16, I am getting an error on any request that uses locals.pocketbase. I can get around this by creating a new client, but that gets painful trying to juggle states.

`await locals.pocketbase.users.authViaEmail(data.email, data.password)`

**Error**
ClientResponseError 404: Something went wrong while processing your request.

Any help is appreciated, thank you!

**Comment by ganigeorgiev** [comment]
@timmyjl12 I cannot reproduce it. I've just installed the latest SvelteKit template with `npm create svelte@latest my-app` and added the example hook from the readme and it works fine for me (the hook file need to be renamed only to `hook.server.js` since SvelteKit now seems to support client-side hooks too, but I'll update the documentation later).

Make sure that you are using the correct url address when instantiating the PocketBase client. If the address is correct, then please provide the full `ClientResponseError` or a repo where it can be reproduced.

**Comment by timmyjl12** [comment]
Hi @ganigeorgiev, thank you for the quick response. Turns out it is the ipv4 resolution. I changed the address from localhost to 127.0.0.1 and all is well. Thank you again.
