### ISSUE TITLE
progress status during upload

### ISSUE THREAD

**Issue by Vanillabacke** [pocketbase/js-sdk#56]
hallo folks,
is there a way to get the progess during uploading files with the sdk?
i was trying it with the realtime.subscribe, but got only the event on completion.

thanks for help / further information,
cheers!

**Comment by ganigeorgiev** [comment]
@Vanillabacke This is not supported at the moment and I don't plan adding it to the SDK since it will complicate too much the internals.

We use `fetch` for sending the API requests and to add file upload progression we will have to add support for streams. This is a little outdated, but you can check the general idea in https://developer.chrome.com/articles/fetch-streaming-requests/#streaming-request-bodies.

Alternatively, you can construct on your own plain old ajax request (aka. `XMLHttpRequest`) and use the native [`upload` events](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/upload):

```js
const data = new FormData()

... 

const request = new XMLHttpRequest();

request.open('POST', '/api/collections/example/records'); 

request.upload.addEventListener('progress', function(e) {
    const percentCompleted = (e.loaded / e.total) * 100;
    console.log(percentCompleted);
});

request.send(data);
```

**Comment by Vanillabacke** [comment]
@ganigeorgiev alright, thanks!
and thank you a lot for your nice work!
