### ISSUE TITLE
How to preserve the session?

### ISSUE THREAD

**Issue by profispojka** [pocketbase/js-sdk#57]
After logging in the user with js-sdk, the session is emptied when pressing F5. How can I preserve the session so that after page refresh the user does not have to log in again.

**Comment by ganigeorgiev** [comment]
@profispojka PocketBase doesn't really have sessions because the API is completely stateless (even the tokens are not stored in the database). In what environment are you using the SDK?

If it is in the browser, the default `AuthStore` uses LocalStorage to keep track of the auth token and model.

For node/deno/react-native - you have to implement it on your own, either via cookie or some other mechanism.
This is usually the case when you are using a SSR framework like SvelteKit, next.js, etc.
The SDK comes with 2 helpers to deal with cookies. Some examples and api guidance you could find in the "SSR integration" section - https://github.com/pocketbase/js-sdk#ssr-integration.

_ps. If you are using the latest pre-release, the documentation could be found in https://github.com/pocketbase/js-sdk/tree/rc#ssr-integration._

**Comment by profispojka** [comment]
@ganigeorgiev Thanks for clarification. I found the data in local storage and edited my app so that it works as it should. So the problem was on my side. By the way this is the best and fastest feedback I got on any Github repo, thanks a lot!
