### ISSUE TITLE
Proposal: make bodyParams generic

### ISSUE THREAD

**Issue by benallfree** [pocketbase/js-sdk#64]
https://github.com/pocketbase/js-sdk/blob/31aae31ab9df9a235e1ea2cf5c4e31e826f13c1f/src/services/RecordService.ts#L112

What about:

```ts
update<T = Record>(id: string, bodyParams : Partial<T> = {}, queryParams = {}): Promise<T> {
```

For that matter, I've been waiting for queryParams to have a type too :)

**Comment by ganigeorgiev** [comment]
But why?

The type shouldn't really matter because the `bodyParams` are an argument and just passed down to fetch. Additionally, `bodyParams` could be a js object or `FormData` instance. We can specify the union types but it shouldn't matter for the end user.

**Comment by benallfree** [comment]
Oh, I didn't realize it was meant to be anything other than a key-value of field names. Do you think every user who is bothered by a lack of field name typing should make their own wrapper? Or is this worth considering further?

Right now, to get intellisense on field names, I have to make a wrapper:

```ts
const updateFields<T=Record> = (id:string, fields:T, queryParams = {})=>client.update(id, fields, queryParams)
await updateFields<MyRecordType>(id, {...})
```

Or:

```ts
const myFields:Partial<MyRecordType> = { ... }
await client.update(id, myFields)
```

**Comment by ganigeorgiev** [comment]
It is hard to generalize. Personally, I wouldn't bother with creating wrappers because it may become too boilerplate-ish, but it depends on your use case, whether your function is frequently called throughout the code, whether there are multiple variants of the arguments, etc.

There is nothing wrong with having a wrapper/extension methods. You can also attach them directly to the `client.prototype` chain if you want to access them as part of the `client` instance, eg:

```js
client.prototype.updateFields = async function () { ... }
```

**Comment by ganigeorgiev** [comment]
I'll close the issue for now because I don't think adding generics support for the crud arguments would help too much with the DX (mostly because there are way too many options and union types doesn't really help), but if anyone thinks otherwise, please comment and I may reconsider it.
