### ISSUE TITLE
"File URL" in "Files upload and handling" example can be improved

### ISSUE THREAD

**Issue by Lex-2008** [pocketbase/js-sdk#7]
I like how nicely you integrated concept of files into the database!

But let me suggest some improvements for the documentation.

I'm talking about this page: https://pocketbase.io/docs/files-handling/, "File URL" section.

In the beginning:
> Each uploaded file could be accessed by requesting its file url:
> ```
> http://localhost:8090/api/files/COLLECTION_ID_OR_NAME/RECORD_ID/FILENAME
> ```

Probably worth mentioning that FILENAME is not name of the file which was uploaded, but rather "RANDOM_STRING_OF_32_CHARACTERS.ORIGINAL_EXTENSION".

It would also answer my original question: what happens if someone tries to upload two different files with a same filename into one field? - Nothing bad, since original filename is lost.

As a sidenote: I don't know how to test it, but I hope that you have some protection in case someone tries to upload a file with a "path traversal" (`/../../`) in extension.

And at the end of this section, this example:
```
// returns something like:
// http://localhost:8090/api/files/demo/9bca0d32-bbc8-4e82-b6a2-08a9dc6e2a19/1234b76.png?thumb=100x250
const url = client.Records.getFileUrl(record, firstFilename, {"thumb": "100x250"});
```
I would update return example to match what it currently returns (with a different style of record ID and filename):
```
http://localhost:8090/api/files/demo/KfZjt5OY8r34HVN/52iWbGINpUXB3prKOPa857IiZRV4RZjL.png?thumb=100x250
```

**Comment by ganigeorgiev** [comment]
About the `/../../` as part of the extension name - this usually shouldn't be supported by the OS and even if you somehow manage to upload a valid file with slashes it will be either ignored or escaped (eg. `__0x2f__..__0x2f__..__0x2f__`).
And further, in PocketBase this doesn't matter because we always set a "root" storage directory path (default to `pb_data/storage`) when intializing the filesystem abstraction and  you can't go outside of that directory (https://github.com/pocketbase/pocketbase/blob/master/core/base.go#L349).

Otherwise, thanks for doc tips. I'll try to update them this evening.

**Comment by ganigeorgiev** [comment]
@Lex-2008 I've updated the [Files upload and handling](https://pocketbase.io/docs/files-handling/) documentation with some of your suggestions.

Thanks again and feel free to let me know if you think its not OK as it is now!
