### ISSUE TITLE
Sometimes an error occurs in the client's request

### ISSUE THREAD

**Issue by jacknion** [pocketbase/js-sdk#77]
Hi,
Sometimes an error occurs in the client's request. I am requesting a localhost address.

Logs:
#############################################
ClientResponseError 0: Something went wrong while processing your request.
    at new i (/root/node_modules/pocketbase/dist/pocketbase.cjs.js:1:2091)
    at /root/node_modules/pocketbase/dist/pocketbase.cjs.js:1:30158
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async insert_alert () {
  url: '',
  status: 0,
  data: {},
  isAbort: true,
  originalError: DOMException [AbortError]: The operation was aborted.
      at Object.fetch (node:internal/deps/undici/undici:11118:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async inserts_alerts ()
}

**Comment by ganigeorgiev** [comment]
This is due to autocancellation (`isAbort: true`), aka. something is triggering your request multiple times without waiting the previous requests to complete.

Autocancellation is enabled by default to prevent async bugs in user land code, but you can disable this behavior if you want to by sending the special query parameter "$autoCancel: false", eg.:

```
// PocketBase JS SDK v0.7.x
client.records.getList("example", 1, 30, { "$autoCancel": false });

// PocketBase JS SDK v0.8.0-rc
client.collection("example").getList(1, 30, { "$autoCancel": false });
``` 

You could find more information and examples for the autocancellation in https://github.com/pocketbase/js-sdk#auto-cancellation.
