### ISSUE TITLE
How to use filter

### ISSUE THREAD

**Issue by Fractal-Tess** [pocketbase/js-sdk#80]
Could you provide some more examples/information on how to use the filter features?

**Comment by ganigeorgiev** [comment]
There are 2 level of filters in PocketBase:

1. Admin level filters (eg. Collection API rules; `@request.*` and `@collection.*` filters can be used only if you are authenticated as admin)
2. Public filters (aka. the `?filter` query param; only the schema fields can be used)

You can find more information and some examples about the rules/filter syntax in:

- https://pocketbase.io/docs/collections/#auth-collection
- https://pocketbase.io/docs/api-rules-and-filters/
- In the API Preview from the Admin UI for each collection

 
It is hard to give a concrete example without context and info of your collections structure, but here is how you can pass a filter using the JS SDK:

```js
// get paginated list of "posts" records that are "active" and after a specific date
// (status and created are fields in the "posts" collection)
const result1 = await pb.collection('posts').getList(1, 20, {
    filter: 'status = "active" && created > "2022-08-01 10:00:00"'
});

// you can even query json or relation fields using the dot-notation
// the below will return all "posts" where the related "anotherSubRelField" records have title that contains the word "hello"
const result2 = await pb.collection('posts').getList(1, 20, {
    filter: 'relField.subRelField.anotherSubRelField.title ~ "hello"'
});
```

_Feel free to open a [Q&A discussion in the main repo](https://github.com/pocketbase/pocketbase/discussions/new) with more information about your use case. If you think that the current documentation could be improved, you can also open a PR in the [static site repo](https://github.com/pocketbase/site)_

**Comment by Fractal-Tess** [comment]
Thank you for the insanely quick answer, @ganigeorgiev 

I I was just about to make another post begging for a related example. 
However, I'm glad to report that your response above clears up this question.

To be perfectly honest this driver is quite a bit different from any other I've used so far. 
There are some things that are still hard to wrap my head around.

Here are a few more questions about the SDK, as I'm hoping to get a better grasp on the design philosophy of the driver.

- Why isn't there a safe CRUD API (methods) that do not throw, and instead return an error object?
- What is the reason for the `ClientResponseError` class not to have underlying types - for example the `data` object
- Isn't it possible to make collections accept a generic with the shape of that table (or I think you call them collections) ?Something like what MongoDB does with their drivers when creating a reference to a collection.
- How would one approach batch CRUDING instead of single operations?
- I don't know if it is just me, but spawning many simultaneous connections at once makes some of them timeout. So, is it possible to define a config for the `pb` instance that automatically retries `x` times or increases the timeout of the fetch calls?

I think this is all I have for now.
Thanks in advance!

**Comment by ganigeorgiev** [comment]
> Why isn't there a safe CRUD API (methods) that do not throw, and instead return an error object?

Throwing errors is a more idiomatic JavaScript since the native methods doesn't return errors. Additionally, returning an error instead of throwing will require to deal with the error handling in multiple places, especially when the `Promise`-based syntax (aka. `then().catch()`) is used.

---

> What is the reason for the ClientResponseError class not to have underlying types - for example the data object

The `ClientresponseError.data` contains information about the submitted the error fields, which API is used. Please also note that some APIs (eg. [collections](https://pocketbase.io/docs/api-collections/)) supports nested fields submission, and the returned error in the `data` will be also nested with the key/index of the error.

---

> Isn't it possible to make collections accept a generic with the shape of that table (or I think you call them collections) ?Something like what MongoDB does with their drivers when creating a reference to a collection.

You can pass a generic resolver type/interface to all crud related methods. For example:
```
await pb.collection("posts").getList<Post>(1, 20);
```
More information you could find in https://github.com/pocketbase/js-sdk#custom-record-types

---

> How would one approach batch CRUDING instead of single operations?

Transactional batch create/update/delete is planned in the future but currently it is not supported.

---

> I don't know if it is just me, but spawning many simultaneous connections at once makes some of them timeout. So, is it possible to define a config for the pb instance that automatically retries x times or increases the timeout of the fetch calls?

This is probably due to the autocancellation. You can disable it for individual requests using the special `$autoCancel` and `$cancelKey` query params or globally for all requests via `pb.autoCancellation(false)`. You can learn more about the autocancellation in https://github.com/pocketbase/js-sdk#auto-cancellation.
