### ISSUE TITLE
Make the library source Deno first.

### ISSUE THREAD

**Issue by tracker1** [pocketbase/js-sdk#9]
- Deno is a very close match for the browser.
- Replace axios with shim around fetch api directly.
- Fetch is in the box for Node 18.x, and can be shimmed with a global declaration `global.fetch = require('node-fetch');` for the node build.

Deno requires a `.ts` as part of the import statement, by doing that change and adding a `/mod.ts` in the root of the project containing `export * from "./src/index.ts` it would be easy enough for deno users to reference from github raw content directly (in the near term).

From there, easy enough to make a clone of the `src/` directory, and remove the `.ts` in the import lines... would only need to change the existing build configuration to make that copy, with the changes, then use `tmp-src` for tests and builds for browser and node usage.

Note: this would make testing slightly more complex... but could probably replace the test harness with Deno's built in testing framework.  Which would simplify dependencies and output.

After that, could do a publish to `https://deno.land/x` to make the package more easy to discover.  I know it may seem backward to suggest targeting the least used platform first, but it would be the easiest path towards the other two.

---

If there's interrest, I'd be happy to help on such a transition.

**Comment by ganigeorgiev** [comment]
Hi,

Because of issues of bundling commonjs modules (axios, qs) and trying to make them work on every environment, I've rewritten the core and have removed the 3rd party dependency in v0.2.0.

Now the library is using only `fetch()` which should be supported by Deno (haven't got the time to test, but the documentation says that it is since Deno v1.0.0).

As a bonus the size was also reduced, from ~75kb to ~23kb (or ~5kb gzipped!).

Please give it a try and share your feedback.

**Comment by ganigeorgiev** [comment]
I'll close the issue for now, because I'm not planning to make the library Deno first, because it will complicate the build process and will introduce some maintenance burden since I'm not very uptodate with Deno.

The recent fetch rewrite should simplify loading the SDK, but if anyone is still having difficulties, feel free to let me know and I'll research it more thoroughly.

**Comment by roj1512** [comment]
The build process won’t be complicated if you use [`deno2node`](https://github.com/fromdeno/deno2node) or [`dnt`](https://github.com/denoland/dnt).

**Comment by roj1512** [comment]
Here’s a Deno-first library we’ve been working on for years, that supports CJS Node.js and browsers as well: https://github.com/grammyjs/grammy

**Comment by tuniverspinner** [comment]
Yo. How things currently stand with Deno & Pocketbase? 
@ganigeorgiev you're still working on Pocketbase? 
If i know more about the issue i may be able to chip in;
